import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";

const Bricolage = Bricolage_Grotesque({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather App by Olawale",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased ${Bricolage.className}`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
